### PR TITLE
Fix generation when consumers/producers are missing from SpecFile

### LINKED ISSUE #197: Maven plugin integration tests are broken

### PR DESCRIPTION
**Pull request by 5uso-sng**
Fixes #197 and #198 (as they were closely related). Mostly updates to the integration tests, but also changes how missing consumers/publishers in SpecFiles are handled.

### CODE REVIEW

File: multiapi-engine/src/main/java/com/sngular/api/generator/plugin/asyncapi/AsyncApiGenerator.java [hunk 1]
```diff
@@ -179,24 +202,22 @@ private void checkRequiredOrCombinatorExists(final SchemaObject schema, final bo
...
-    referenceList.forEach(reference ->
-        processReference(node, reference, ymlParentPath, totalSchemas, referenceList)
-    );
+    referenceList.forEach(reference -> processReference(node, reference, ymlParentPath, totalSchemas, referenceList));
     final List<JsonNode> messagesList = node.findValues(MESSAGES);
     final List<JsonNode> schemasList = node.findValues(SCHEMAS);
-    schemasList.forEach(schema -> schema.fields().forEachRemaining(fieldSchema -> totalSchemas.putIfAbsent((SCHEMAS + SLASH + fieldSchema.getKey()).toUpperCase(),
-                                                                   fieldSchema.getValue())));
+    schemasList.forEach(
+        schema -> schema.fields().forEachRemaining(fieldSchema -> totalSchemas.putIfAbsent((SCHEMAS + SLASH + fieldSchema.getKey()).toUpperCase(), fieldSchema.getValue())));
```
Comment (josemenvegsngular) [inline multiapi-engine/src/main/java/com/sngular/api/generator/plugin/asyncapi/AsyncApiGenerator.java:209]: Due to the code `SCHEMAS +SLASH +fieldSchema.getKey()` is repeated, at least three times (L. 209, 215 and 217), may be it should be a good idea to extract its value to a constant to avoid repeating the same code.

File: multiapi-engine/src/main/java/com/sngular/api/generator/plugin/asyncapi/AsyncApiGenerator.java [hunk 2]
```diff
@@ -160,6 +153,36 @@ public final void processFileSpec(final List<SpecFile> specsListFile) {
     }
   }
 
+  private void handleMissingPublisherConsumer(final SpecFile fileParameter, final JsonNode channel, final String operationId) {
+    if (channel.has(SUBSCRIBE) && ObjectUtils.allNull(fileParameter.getConsumer(), fileParameter.getStreamBridge())) {
```
Comment (josemenvegsngular) [inline multiapi-engine/src/main/java/com/sngular/api/generator/plugin/asyncapi/AsyncApiGenerator.java:157]: Lines 157-169 and L.171-182 are very similar.
May be we can made a refactor for common code, the first thing that I see:
```
var parameter = OperationParameterObject.builder()
                                    .ids(operationId)
                                    .apiPackage(DEFAULT_ASYNCAPI_API_PACKAGE)
                                    .modelPackage(DEFAULT_ASYNCAPI_MODEL_PACKAGE)
                                    .build());
...
     try {
        checkClassPackageDuplicate(CONSUMER_CLASS_NAME, DEFAULT_ASYNCAPI_API_PACKAGE);
        fileParameter.setConsumer(parameter);
      } catch (final DuplicateClassException ignored) {
        // Don't set consumer
      }
    }
...
fileParameter.setSupplier(parameter);
...
```

**Review by davidgayoso — COMMENTED** [review]
Apart from the comments Jose María made, everything seems to be correct. Good job.

**Comment by josemenvegsngular** [comment]
As I have said, change the code proposed if you like and feel confortable with them (or if you have a better idea, discard what I have propose)

**Comment by 5uso-sng** [comment]
> As I have said, change the code proposed if you like and feel confortable with them (or if you have a better idea, discard what I have propose)

Yeah, don't worry about it. I'm always up for changes improving code readability!

**Review by janDuinRod — APPROVED** [review]

**Review by davidgayoso — APPROVED** [review]

**Comment by 5uso-sng** [comment]
I think updating this branch from main should make the integration tests run now
