### PR TITLE
NullPointerException when processing a YML with no "components"

### LINKED ISSUE #226: [OpenAPI] NullPointerException when processing a YML with no "components"
```
openapi: 3.0.2
info:
  title: Testing example file
  version: 1.0.0
servers:
- url: http://localhost/v1
paths:
  /test:
    get:
      tags:
      - test
      operationId: testNoComponents
      responses:
        '200':
          description: A string
          content:
            application/json:
              schema:
                type: string
```

A YML file like this one causes a NullPointerException when running the plugin due to the missing "components". However, it is still a valid specification.

### PR DESCRIPTION
**Pull request by davidgayoso**
Fixes #226.

### CODE REVIEW

File: multiapi-engine/src/main/java/com/sngular/api/generator/plugin/openapi/utils/MapperPathUtil.java [hunk 1]
```diff
@@ -47,12 +48,21 @@ private MapperPathUtil() {}
...
-                       .build();
+    if (Objects.nonNull(openAPI.getComponents())){
+      return GlobalObject.builder()
+                         .url(openAPI.getServers().get(0).getUrl())
+                         .authSchemas(authSchemaList)
+                         .authentications(authList)
+                         .schemaMap(openAPI.getComponents().getSchemas())
+                         .build();
+    }else{
+      return GlobalObject.builder()
```
Comment (5uso-sng) [inline multiapi-engine/src/main/java/com/sngular/api/generator/plugin/openapi/utils/MapperPathUtil.java:59]: Make sure to run the autoformatter

Comment (davidgayoso) [reply multiapi-engine/src/main/java/com/sngular/api/generator/plugin/openapi/utils/MapperPathUtil.java]: Fixed

File: multiapi-engine/src/main/java/com/sngular/api/generator/plugin/openapi/utils/MapperPathUtil.java [hunk 2]
```diff
@@ -47,12 +48,21 @@ private MapperPathUtil() {}
...
     final var authList = getSecurityRequirementList(openAPI.getSecurity(), new ArrayList<>());
-    return GlobalObject.builder()
-                       .url(openAPI.getServers().get(0).getUrl())
-                       .authSchemas(authSchemaList)
-                       .authentications(authList)
-                       .schemaMap(openAPI.getComponents().getSchemas())
-                       .build();
+    if (Objects.nonNull(openAPI.getComponents())){
+      return GlobalObject.builder()
+                         .url(openAPI.getServers().get(0).getUrl())
```
[the remark this answers is not in the document]
Comment (davidgayoso) [reply multiapi-engine/src/main/java/com/sngular/api/generator/plugin/openapi/utils/MapperPathUtil.java]: Fixed

File: multiapi-engine/src/main/java/com/sngular/api/generator/plugin/openapi/utils/MapperPathUtil.java [hunk 3]
```diff
@@ -47,12 +47,13 @@ private MapperPathUtil() {}
...
-                       .authentications(authList)
-                       .schemaMap(openAPI.getComponents().getSchemas())
-                       .build();
+    final GlobalObject globalObject = GlobalObject.builder().url(openAPI.getServers().get(0).getUrl()).authSchemas(authSchemaList).authentications(authList).build();
+    if (Objects.nonNull(openAPI.getComponents())) {
+      globalObject.setSchemaMap(openAPI.getComponents().getSchemas());
+    } else {
+      globalObject.setSchemaMap(Collections.emptyMap());
+    }
+    return globalObject;
```
Comment (5uso-sng) [inline multiapi-engine/src/main/java/com/sngular/api/generator/plugin/openapi/utils/MapperPathUtil.java:56]: Since this is a builder, a more appropiate way of doing this would be:
```suggestion
    final GlobalObject globalObject = GlobalObject.builder().url(openAPI.getServers().get(0).getUrl()).authSchemas(authSchemaList).authentications(authList);
    globalObject.schemaMap(Objects.nonNull(openAPI.getComponents()) ? openAPI.getComponents().getSchemas() : Collections.emptyMap());
    return globalObject.build();
```

**Review by 5uso-sng — APPROVED** [review]
